### ISSUE TITLE
Runes

### ISSUE THREAD

**Issue by JeseGamerHD** [JeseGamerHD/AssortedAdditions#122]
Runes can be equipped in the Rune Slot which is unlocked by using a Blank Rune.

List of runes:

- **Blank Rune**: Using it unlocks the Rune Slot. Also used in crafting.  
Drops from: Tim (100%), Dark Caster (4%), Goblin Sorcerer (4%), Fire Imp (4%) or the Rune Wizard (33%), breaking Pots (1/125). 
Sold by Wizard. 

- **Rune of Spelunking**: 20% increased mining speed, improved night vision, highlights ore/treasure. Found in golden chests and sold by skeleton merchant.

- **Rune of Death**: Found in Dead Man's Chests. Grants immunity to traps..

- **Rune of Movement**: Grants the ability to dash. Can be found in locked golden chests. Can also be crafted: Blank Rune + Shield of Cthulhu + 5 Soul of Flight.

- **Rune of Health**: Enemies are more likely to drop health when killed. Allows the player to heal 300 health when pressing the rune ability key (3min cooldown). Crafted with Blank Rune + 10 Magic Essence + 3 Life Crystal. Sometimes drops from Rune Wizard.

- **Mana Rune**: 50% increased max mana. Enemies are more likely to drop mana stars when killed. Crafted with Blank Rune + 10 Magic Essence + 3 Mana Crystal. Sometimes drops from Rune Wizard.

- **Rune of Shadows**: All attacks inflict shadowflames. Summons protective orbs. Has a special ability. Crafted with Blank Rune + Shadow Orb + Soul of Might + Soul of Sight + Soul of Fright.

- **Rune of Relocation**: Allows the player to teleport to their cursor position when pressing rune ability key. Has a cooldown. Sold by the Steampunker.

- **Rune of Prosperity**:  Enemies killed will drop more money. Mined ores have a chance to drop an additional ore. Crafted with: Blank Rune + 30 Gold Dust + 50 Gold Coins. Dropped by pirate event enemies (1% chance) and by the Pirate Ship (6.7%)

- **Rune of Flight**: Allows flight and slow fall. Crafted with: Blank Rune + 10 Magic Essence + 20 Soul of Flight

- **Rune of Guarding**: Pressing the rune ability key summons a Rune Sentry. Increases your max number of minions by 2. Crafted with: Life Fruit + Blank Rune + 3 Hallowed Bar + 10 Magic Essence. Sold by the Witch Doctor after defeating any mech boss.

**Comment by Chrys-02142008** [comment]
HOW do I use a blank rune? I figured it was consumable, but it doesn't say it is. I tried anyway, but it didn't work. I can't equip it or anything.

**Comment by JeseGamerHD** [comment]
> HOW do I use a blank rune? I figured it was consumable, but it doesn't say it is. I tried anyway, but it didn't work. I can't equip it or anything.

You should be able to use it just like the Mana Crystal or Life Crystal. Are you sure the slot did not already unlock by trying to use it? It should play a sound and the slot's icon should change. The item itself does not get consumed. Everything seems to be working on my end.
